spring:
  application:
    name: zb-consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /myHealthCheck
        health-check-interval: 20s
        enabled: true
        instance-id: ${spring.application.name}:${random.value}
server:
  port: 8000